export * from "./expediente_m_route";
export * from "./fisiologias_m_route";
export * from "./gasto_fijo_m_route";
export * from "./lote_m_route";
export * from "./mascota_m_route";
export * from "./producto_m_route";
export * from "./producto_venta_m_route";
export * from "./usuario_m_route";
export * from "./veterinaria_m_route";
